import { APP_NAME } from './data/data';

export const SEARCHABLE_TOOLS = [
  { name: 'Home', path: '/', category: APP_NAME },
  { name: 'All Calculators', path: '/all.html', category: APP_NAME },
  { name: 'EMI Calculator', path: '/emi-calculator.html', category: 'Financial' },
  { name: 'Compound Interest Calculator', path: '/compound-interest-calculator.html', category: 'Financial' },
  { name: 'Simple Interest Calculator', path: '/simple-interest-calculator.html', category: 'Financial' },
  { name: 'SIP Calculator', path: '/sip-calculator.html', category: 'Financial' },
  { name: 'Loan Calculator', path: '/loan-calculator.html', category: 'Financial' },
  { name: 'Mortgage Calculator', path: '/mortgage-calculator.html', category: 'Financial' },
  { name: 'Tax Calculator', path: '/tax-calculator.html', category: 'Financial' },
  { name: 'Retirement Calculator', path: '/retirement-calculator.html', category: 'Financial' },
  { name: 'Investment Calculator', path: '/investment-calculator.html', category: 'Financial' },
  { name: 'BMI Calculator', path: '/bmi-calculator.html', category: 'Health' },
  { name: 'BMR Calculator', path: '/bmr-calculator.html', category: 'Health' },
  { name: 'Calorie Calculator', path: '/calorie-calculator.html', category: 'Health' },
  { name: 'TDEE Calculator', path: '/tdee-calculator.html', category: 'Health' },
  { name: 'Body Fat Calculator', path: '/body-fat-calculator.html', category: 'Health' },
  { name: 'Water Intake Calculator', path: '/water-intake-calculator.html', category: 'Health' },
  { name: 'Ideal Weight Calculator', path: '/ideal-weight-calculator.html', category: 'Health' },
  { name: 'Pregnancy Calculator', path: '/pregnancy-calculator.html', category: 'Health' },
  { name: 'Percentage Calculator', path: '/percentage-calculator.html', category: 'Math' },
  { name: 'Fraction Calculator', path: '/fraction-calculator.html', category: 'Math' },
  { name: 'Square Root Calculator', path: '/square-root-calculator.html', category: 'Math' },
  { name: 'Average Calculator', path: '/average-calculator.html', category: 'Math' },
  { name: 'GCD Calculator', path: '/gcd-calculator.html', category: 'Math' },
  { name: 'LCM Calculator', path: '/lcm-calculator.html', category: 'Math' },
  { name: 'Age Calculator', path: '/age-calculator.html', category: 'DateTime' },
  { name: 'Date Calculator', path: '/date-calculator.html', category: 'DateTime' },
  { name: 'Date Difference Calculator', path: '/date-difference-calculator.html', category: 'DateTime' },
  { name: 'Scientific Calculator', path: '/scientific-calculator.html', category: 'Scientific' },
  { name: 'Trigonometry Calculator', path: '/trigonometry-calculator.html', category: 'Scientific' },
  { name: 'Unit Converter', path: '/unit-conversion-calculator.html', category: 'Scientific' },
  { name: 'Binary Converter', path: '/binary-hex-decimal-converter.html', category: 'Programming' },
  { name: 'JSON Formatter', path: '/json-formatter.html', category: 'Programming' },
  { name: 'Hash Generator', path: '/hash-generator.html', category: 'Programming' },
  { name: 'Base64 Encoder', path: '/base64-encoder.html', category: 'Programming' },
  { name: 'Bitwise Calculator', path: '/bitwise-calculator.html', category: 'Programming' },
  { name: 'Concrete Calculator', path: '/concrete-calculator.html', category: 'Construction' },
  { name: 'Tile Calculator', path: '/tile-calculator.html', category: 'Construction' },
  { name: 'Paint Calculator', path: '/paint-calculator.html', category: 'Construction' },
  { name: 'P&L Calculator', path: '/pnl-calculator.html', category: 'Trading' },
  { name: 'Position Size Calculator', path: '/position-size-calculator.html', category: 'Trading' },
  { name: 'Risk Reward Calculator', path: '/risk-reward-calculator.html', category: 'Trading' },
  { name: 'Stop Loss Calculator', path: '/stop-loss-calculator.html', category: 'Trading' },
  { name: 'CAGR Calculator', path: '/cagr-calculator.html', category: 'Trading' },
  { name: 'Notepad', path: '/notepad.html', category: 'Tools' },
];